# Generated by Django 3.2 on 2022-08-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_examination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='diagnosis',
            field=models.CharField(max_length=100),
        ),
    ]
