# Generated by Django 3.2 on 2022-08-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_examination_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='treatment',
            field=models.CharField(max_length=100),
        ),
    ]
